// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 4.7.2 by WSRD Tencent.
// Generated from `Cdtp.jce'
// **********************************************************************

#ifndef __CDTP_H_
#define __CDTP_H_

#include <map>
#include <string>
#include <vector>
#include "tmtp.h"
#include "jce/Jce.h"

using namespace std;


namespace Toon
{

}



#endif
